# Generated by Django 2.0.2 on 2018-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogbreeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('coat', models.CharField(max_length=200)),
                ('drools', models.BooleanField()),
                ('goodWC', models.BooleanField()),
                ('grooming', models.CharField(max_length=200)),
                ('intelligence', models.CharField(max_length=200)),
                ('shedding', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
