# Generated by Django 2.0.4 on 2018-06-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180616_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='General Knowledge', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=200),
        ),
    ]
